// ─────────────────────────────────────────────────────────────────────────────
// data.js  –  Static reference data: Bible books and translations
// ─────────────────────────────────────────────────────────────────────────────

// verses[i] = max verse count for chapter (i+1) of that book
const BIBLE_BOOKS = [
  // ── Old Testament ──────────────────────────────────────────────────────────
  { name: 'Genesis',         abbr: 'Gen',   testament: 'OT', maxChapters: 50,
    verses: [31,25,24,26,32,22,24,22,29,32,32,20,18,24,21,16,27,33,38,18,34,24,20,67,34,35,46,22,35,43,54,33,20,31,29,43,36,30,23,23,57,38,34,34,28,34,31,22,33,26] },
  { name: 'Exodus',          abbr: 'Exod',  testament: 'OT', maxChapters: 40,
    verses: [22,25,22,31,23,30,25,32,35,29,10,51,22,31,27,36,16,27,25,26,36,31,33,18,40,37,21,43,46,38,18,35,23,35,35,38,29,31,43,38] },
  { name: 'Leviticus',       abbr: 'Lev',   testament: 'OT', maxChapters: 27,
    verses: [17,16,17,35,19,30,38,36,24,20,47,8,59,57,33,34,16,30,37,27,24,33,44,23,55,46,34] },
  { name: 'Numbers',         abbr: 'Num',   testament: 'OT', maxChapters: 36,
    verses: [54,34,51,49,31,27,89,26,23,36,35,16,33,45,41,50,13,32,22,29,35,41,30,25,18,65,23,31,40,16,54,42,56,29,34,13] },
  { name: 'Deuteronomy',     abbr: 'Deut',  testament: 'OT', maxChapters: 34,
    verses: [46,37,29,49,33,25,26,20,29,22,32,32,18,29,23,22,20,22,21,20,23,30,25,22,19,19,26,68,29,20,30,52,29,12] },
  { name: 'Joshua',          abbr: 'Josh',  testament: 'OT', maxChapters: 24,
    verses: [18,24,17,24,15,27,26,35,27,43,23,24,33,15,63,10,18,28,51,9,45,34,16,33] },
  { name: 'Judges',          abbr: 'Judg',  testament: 'OT', maxChapters: 21,
    verses: [36,23,31,24,31,40,25,35,57,18,40,15,25,20,20,31,13,31,30,48,25] },
  { name: 'Ruth',            abbr: 'Ruth',  testament: 'OT', maxChapters: 4,
    verses: [22,23,18,22] },
  { name: '1 Samuel',        abbr: '1 Sam', testament: 'OT', maxChapters: 31,
    verses: [28,36,21,22,12,21,17,22,27,27,15,25,23,52,35,23,58,30,24,42,15,23,29,22,44,25,12,25,11,31,13] },
  { name: '2 Samuel',        abbr: '2 Sam', testament: 'OT', maxChapters: 24,
    verses: [27,32,39,12,25,23,29,18,13,19,27,31,39,33,37,23,29,33,43,26,22,51,39,25] },
  { name: '1 Kings',         abbr: '1 Kgs', testament: 'OT', maxChapters: 22,
    verses: [53,46,28,34,18,38,51,66,28,29,43,33,34,31,34,34,24,46,21,43,29,53] },
  { name: '2 Kings',         abbr: '2 Kgs', testament: 'OT', maxChapters: 25,
    verses: [18,25,27,44,27,33,20,29,37,36,21,21,25,29,38,20,41,37,37,21,26,20,37,20,30] },
  { name: '1 Chronicles',    abbr: '1 Chr', testament: 'OT', maxChapters: 29,
    verses: [54,55,24,43,26,81,40,40,44,14,47,40,14,17,29,43,27,17,19,8,30,19,32,31,31,32,34,21,30] },
  { name: '2 Chronicles',    abbr: '2 Chr', testament: 'OT', maxChapters: 36,
    verses: [17,18,17,22,14,42,22,18,31,19,23,16,22,15,19,14,19,34,11,37,20,12,21,27,28,23,9,27,36,27,21,33,25,33,27,23] },
  { name: 'Ezra',            abbr: 'Ezra',  testament: 'OT', maxChapters: 10,
    verses: [11,70,13,24,17,22,28,36,15,44] },
  { name: 'Nehemiah',        abbr: 'Neh',   testament: 'OT', maxChapters: 13,
    verses: [11,20,32,23,19,19,73,18,38,39,36,47,31] },
  { name: 'Esther',          abbr: 'Esth',  testament: 'OT', maxChapters: 10,
    verses: [22,23,15,17,14,14,10,17,32,3] },
  { name: 'Job',             abbr: 'Job',   testament: 'OT', maxChapters: 42,
    verses: [22,13,26,21,27,30,21,22,35,22,20,25,28,22,35,22,16,21,29,29,34,30,17,25,6,14,23,28,25,31,40,22,33,37,16,33,24,41,30,24,34,17] },
  { name: 'Psalms',          abbr: 'Ps',    testament: 'OT', maxChapters: 150,
    verses: [6,12,8,8,12,10,17,9,20,18,7,8,6,7,5,11,15,50,14,9,13,31,6,10,22,12,14,9,11,12,24,11,22,22,28,12,40,22,13,17,13,11,5,26,17,11,9,14,20,23,19,9,6,7,23,13,11,11,17,12,8,12,11,10,13,20,7,35,36,5,24,20,28,23,10,12,20,72,13,19,16,8,18,12,13,17,7,18,52,17,16,15,5,23,11,13,12,9,9,5,8,28,22,35,45,48,43,13,31,7,10,10,9,8,18,19,2,29,176,7,8,9,4,8,5,6,5,6,8,8,3,18,3,3,21,26,9,8,24,13,10,7,12,15,21,10,20,14,9,6] },
  { name: 'Proverbs',        abbr: 'Prov',  testament: 'OT', maxChapters: 31,
    verses: [33,22,35,27,23,35,27,22,18,32,31,28,25,35,33,33,28,24,29,30,31,29,35,34,28,28,27,28,27,33,31] },
  { name: 'Ecclesiastes',    abbr: 'Eccl',  testament: 'OT', maxChapters: 12,
    verses: [18,26,22,16,20,12,29,17,18,20,10,14] },
  { name: 'Song of Solomon', abbr: 'Song',  testament: 'OT', maxChapters: 8,
    verses: [17,17,11,16,16,13,13,14] },
  { name: 'Isaiah',          abbr: 'Isa',   testament: 'OT', maxChapters: 66,
    verses: [31,22,26,6,30,13,25,22,21,34,16,6,22,32,9,14,14,7,25,6,17,25,18,23,12,21,13,29,24,33,9,20,24,17,10,22,38,22,8,31,29,25,28,28,25,13,15,22,26,11,23,15,12,17,13,12,21,14,21,22,11,12,19,12,25,24] },
  { name: 'Jeremiah',        abbr: 'Jer',   testament: 'OT', maxChapters: 52,
    verses: [19,37,25,31,31,30,34,22,26,25,23,17,27,22,21,21,27,23,15,18,14,30,40,10,38,24,22,17,32,24,40,44,26,22,19,32,21,28,18,16,18,22,13,30,5,28,7,47,39,46,64,34] },
  { name: 'Lamentations',    abbr: 'Lam',   testament: 'OT', maxChapters: 5,
    verses: [22,22,66,22,22] },
  { name: 'Ezekiel',         abbr: 'Ezek',  testament: 'OT', maxChapters: 48,
    verses: [28,10,27,17,17,14,27,18,11,22,25,28,23,23,8,63,24,32,14,49,32,31,49,27,17,21,36,26,21,26,18,32,33,31,15,38,28,23,29,49,26,20,27,31,25,24,23,35] },
  { name: 'Daniel',          abbr: 'Dan',   testament: 'OT', maxChapters: 12,
    verses: [21,49,30,37,31,28,28,27,27,21,45,13] },
  { name: 'Hosea',           abbr: 'Hos',   testament: 'OT', maxChapters: 14,
    verses: [11,23,5,19,15,11,16,14,17,15,12,14,16,9] },
  { name: 'Joel',            abbr: 'Joel',  testament: 'OT', maxChapters: 3,
    verses: [20,32,21] },
  { name: 'Amos',            abbr: 'Amos',  testament: 'OT', maxChapters: 9,
    verses: [15,16,15,13,27,14,17,14,15] },
  { name: 'Obadiah',         abbr: 'Obad',  testament: 'OT', maxChapters: 1,
    verses: [21] },
  { name: 'Jonah',           abbr: 'Jonah', testament: 'OT', maxChapters: 4,
    verses: [17,10,10,11] },
  { name: 'Micah',           abbr: 'Mic',   testament: 'OT', maxChapters: 7,
    verses: [16,13,12,13,15,16,20] },
  { name: 'Nahum',           abbr: 'Nah',   testament: 'OT', maxChapters: 3,
    verses: [15,13,19] },
  { name: 'Habakkuk',        abbr: 'Hab',   testament: 'OT', maxChapters: 3,
    verses: [17,20,19] },
  { name: 'Zephaniah',       abbr: 'Zeph',  testament: 'OT', maxChapters: 3,
    verses: [18,15,20] },
  { name: 'Haggai',          abbr: 'Hag',   testament: 'OT', maxChapters: 2,
    verses: [15,23] },
  { name: 'Zechariah',       abbr: 'Zech',  testament: 'OT', maxChapters: 14,
    verses: [21,13,10,14,11,15,14,23,17,12,17,14,9,21] },
  { name: 'Malachi',         abbr: 'Mal',   testament: 'OT', maxChapters: 4,
    verses: [14,17,18,6] },
  // ── New Testament ──────────────────────────────────────────────────────────
  { name: 'Matthew',         abbr: 'Matt',  testament: 'NT', maxChapters: 28,
    verses: [25,23,17,25,48,34,29,34,38,42,30,50,58,36,39,28,27,35,30,34,46,46,39,51,46,75,66,20] },
  { name: 'Mark',            abbr: 'Mark',  testament: 'NT', maxChapters: 16,
    verses: [45,28,35,41,43,56,37,38,50,52,33,44,37,72,47,20] },
  { name: 'Luke',            abbr: 'Luke',  testament: 'NT', maxChapters: 24,
    verses: [80,52,38,44,39,49,50,56,62,42,54,59,35,35,32,31,37,43,48,47,38,71,56,53] },
  { name: 'John',            abbr: 'John',  testament: 'NT', maxChapters: 21,
    verses: [51,25,36,54,47,71,53,59,41,42,57,50,38,31,27,33,26,40,42,31,25] },
  { name: 'Acts',            abbr: 'Acts',  testament: 'NT', maxChapters: 28,
    verses: [26,47,26,37,42,15,60,40,43,48,30,25,52,28,41,40,34,28,41,38,40,30,35,27,27,32,44,31] },
  { name: 'Romans',          abbr: 'Rom',   testament: 'NT', maxChapters: 16,
    verses: [32,29,31,25,21,23,25,39,33,21,36,21,14,23,33,27] },
  { name: '1 Corinthians',   abbr: '1 Cor', testament: 'NT', maxChapters: 16,
    verses: [31,16,23,21,13,20,40,13,27,33,34,31,13,40,58,24] },
  { name: '2 Corinthians',   abbr: '2 Cor', testament: 'NT', maxChapters: 13,
    verses: [24,17,18,18,21,18,16,24,15,18,33,21,14] },
  { name: 'Galatians',       abbr: 'Gal',   testament: 'NT', maxChapters: 6,
    verses: [24,21,29,31,26,18] },
  { name: 'Ephesians',       abbr: 'Eph',   testament: 'NT', maxChapters: 6,
    verses: [23,22,21,32,33,24] },
  { name: 'Philippians',     abbr: 'Phil',  testament: 'NT', maxChapters: 4,
    verses: [30,30,21,23] },
  { name: 'Colossians',      abbr: 'Col',   testament: 'NT', maxChapters: 4,
    verses: [29,23,25,18] },
  { name: '1 Thessalonians', abbr: '1 Th',  testament: 'NT', maxChapters: 5,
    verses: [10,20,13,18,28] },
  { name: '2 Thessalonians', abbr: '2 Th',  testament: 'NT', maxChapters: 3,
    verses: [12,17,18] },
  { name: '1 Timothy',       abbr: '1 Tim', testament: 'NT', maxChapters: 6,
    verses: [20,15,16,16,25,21] },
  { name: '2 Timothy',       abbr: '2 Tim', testament: 'NT', maxChapters: 4,
    verses: [18,26,17,22] },
  { name: 'Titus',           abbr: 'Titus', testament: 'NT', maxChapters: 3,
    verses: [16,15,15] },
  { name: 'Philemon',        abbr: 'Phlm',  testament: 'NT', maxChapters: 1,
    verses: [25] },
  { name: 'Hebrews',         abbr: 'Heb',   testament: 'NT', maxChapters: 13,
    verses: [14,18,19,16,14,20,28,13,28,39,40,29,25] },
  { name: 'James',           abbr: 'Jas',   testament: 'NT', maxChapters: 5,
    verses: [27,26,18,17,20] },
  { name: '1 Peter',         abbr: '1 Pet', testament: 'NT', maxChapters: 5,
    verses: [25,25,22,19,14] },
  { name: '2 Peter',         abbr: '2 Pet', testament: 'NT', maxChapters: 3,
    verses: [21,22,18] },
  { name: '1 John',          abbr: '1 Jn',  testament: 'NT', maxChapters: 5,
    verses: [10,29,24,21,21] },
  { name: '2 John',          abbr: '2 Jn',  testament: 'NT', maxChapters: 1,
    verses: [13] },
  { name: '3 John',          abbr: '3 Jn',  testament: 'NT', maxChapters: 1,
    verses: [14] },
  { name: 'Jude',            abbr: 'Jude',  testament: 'NT', maxChapters: 1,
    verses: [25] },
  { name: 'Revelation',      abbr: 'Rev',   testament: 'NT', maxChapters: 22,
    verses: [20,29,22,11,14,17,17,13,21,11,19,17,18,20,8,21,18,24,21,15,27,21] },
];

const TRANSLATIONS = [
  // ── Major BibleGateway-supported English translations ─────────────────────
  { abbr: 'NIV',      name: 'New International Version', bg: true },
  { abbr: 'NIVUK',    name: 'New International Version (UK)', bg: true },
  { abbr: 'NLT',      name: 'New Living Translation', bg: true },
  { abbr: 'ESV',      name: 'English Standard Version', bg: true },
  { abbr: 'ESVUK',    name: 'English Standard Version Anglicised', bg: true },
  { abbr: 'KJV',      name: 'King James Version', bg: true },
  { abbr: 'NKJV',     name: 'New King James Version', bg: true },
  { abbr: 'NASB',     name: 'New American Standard Bible', bg: true },
  { abbr: 'NASB95',   name: 'NASB 1995', bg: true },
  { abbr: 'LSB',      name: 'Legacy Standard Bible', bg: true },
  { abbr: 'CSB',      name: 'Christian Standard Bible', bg: true },
  { abbr: 'HCSB',     name: 'Holman Christian Standard Bible', bg: true },
  { abbr: 'NET',      name: 'New English Translation', bg: true },
  { abbr: 'CEB',      name: 'Common English Bible', bg: true },
  { abbr: 'NRSVUE',   name: 'New Revised Standard Version, Updated Edition', bg: true },
  { abbr: 'NRSVA',    name: 'New Revised Standard Version', bg: true },
  { abbr: 'NRSVCE',   name: 'New Revised Standard Version Catholic Edition', bg: true },
  { abbr: 'RSV',      name: 'Revised Standard Version', bg: true },
  { abbr: 'RSVCE',    name: 'Revised Standard Version Catholic Edition', bg: true },
  { abbr: 'AMP',      name: 'Amplified Bible', bg: true },
  { abbr: 'AMPC',     name: 'Amplified Bible, Classic Edition', bg: true },
  { abbr: 'MSG',      name: 'The Message', bg: true },
  { abbr: 'TLB',      name: 'The Living Bible', bg: true },
  { abbr: 'VOICE',    name: 'The Voice', bg: true },
  { abbr: 'ISV',      name: 'International Standard Version', bg: true },
  { abbr: 'MEV',      name: 'Modern English Version', bg: true },
  { abbr: 'ICB',      name: "International Children's Bible", bg: true },
  { abbr: 'NIRV',     name: 'New International Reader’s Version', bg: true },
  { abbr: 'NCV',      name: 'New Century Version', bg: true },
  { abbr: 'CEV',      name: 'Contemporary English Version', bg: true },
  { abbr: 'GNT',      name: 'Good News Translation', bg: true },
  { abbr: 'GW',       name: "GOD'S WORD Translation", bg: true },
  { abbr: 'ASV',      name: 'American Standard Version', bg: true },
  { abbr: 'YLT',      name: "Young's Literal Translation", bg: true },
  { abbr: 'DARBY',    name: 'Darby Translation', bg: true },
  { abbr: 'GNV',      name: 'Geneva Bible', bg: false },
  { abbr: 'CPDV',     name: 'Catholic Public Domain Version', bg: false },
  { abbr: 'WEB',      name: 'World English Bible', bg: true },
  { abbr: 'NABRE',    name: 'New American Bible, Revised Edition', bg: true },
  { abbr: 'BSB',      name: 'Berean Standard Bible', bg: false }, // from helloao free source

  // ── Indic Languages (free sources) ────────────────────────────────────────
  { abbr: 'ERV-HI',   name: 'Hindi Bible: Easy-to-Read Version', bg: true, lang: 'hi' },
  { abbr: 'SHB',      name: 'Saral Hindi Bible', bg: true, lang: 'hi' },
  { abbr: 'HINOVBSI', name: 'Hindi O.V. (BSI)', bg: false, lang: 'hi' },

  { abbr: 'ERV-TA',   name: 'Tamil Bible: Easy-to-Read Version', bg: true, lang: 'ta' },
  { abbr: 'TAOVBSI',  name: 'Tamil O.V. (BSI)', bg: false, lang: 'ta' },

  { abbr: 'TERV',     name: 'Telugu Holy Bible: Easy-to-Read Version', bg: true, lang: 'te' },
  { abbr: 'IRVTEL',   name: 'Telugu IRV', bg: false, lang: 'te' },

  { abbr: 'MALOVBSI', name: 'Malayalam O.V. (BSI)', bg: false, lang: 'ml' },
  { abbr: 'MALCLBSI', name: 'Malayalam CL (BSI)', bg: false, lang: 'ml' },
  { abbr: 'KERV',     name: 'Kannada Holy Bible: Easy-to-Read Version', bg: true, lang: 'kn' },

  // ── Available in current premium API integration (and maybe free elsewhere) ─
  { abbr: 'LSV',      name: 'Literal Standard Version', bg: false },

  // ── Legacy aliases retained for compatibility with existing presets ───────
  { abbr: 'NRSV',     name: 'New Revised Standard Version (legacy alias)', bg: true },
  { abbr: 'NIV84',    name: 'New International Version (1984)', bg: false },
];

// ── bible-api.com  (free, no key, public-domain translations) ─────────────────
// Maps our translation abbreviations to bible-api.com ?translation= parameters.
const BIBLE_API_MAP = {
  'KJV':   'kjv',
  'ASV':   'asv',
  'WEB':   'web',
  'YLT':   'ylt',
  'DARBY': 'darby',
  'BBE':   'bbe',
};

// ── BibleGateway version code mapping ────────────────────────────────────────
// Translation abbreviations in our UI mapped to BibleGateway version codes.
const BIBLEGATEWAY_MAP = {
  'NIV': 'NIV',
  'NIVUK': 'NIVUK',
  'NLT': 'NLT',
  'ESV': 'ESV',
  'ESVUK': 'ESVUK',
  'KJV': 'KJV',
  'NKJV': 'NKJV',
  'NASB': 'NASB',
  'NASB95': 'NASB1995',
  'LSB': 'LSB',
  'CSB': 'CSB',
  'HCSB': 'HCSB',
  'NET': 'NET',
  'CEB': 'CEB',
  'NRSVUE': 'NRSVUE',
  'NRSVA': 'NRSVA',
  'NRSVCE': 'NRSVCE',
  'NRSV': 'NRSVA',
  'RSV': 'RSV',
  'RSVCE': 'RSVCE',
  'AMP': 'AMP',
  'AMPC': 'AMPC',
  'MSG': 'MSG',
  'TLB': 'TLB',
  'VOICE': 'VOICE',
  'ISV': 'ISV',
  'MEV': 'MEV',
  'ICB': 'ICB',
  'NIRV': 'NIRV',
  'NCV': 'NCV',
  'CEV': 'CEV',
  'GNT': 'GNT',
  'GW': 'GW',
  'ASV': 'ASV',
  'YLT': 'YLT',
  'DARBY': 'DARBY',
  'WEB': 'WEB',
  'NABRE': 'NABRE',
  'ERV-HI': 'ERV-HI',
  'SHB': 'SHB',
  'ERV-TA': 'ERV-TA',
  'TERV': 'TERV',
  'KERV': 'KERV',
};

// ── YouVersion mapping (supported in Glowstudent777/YouVersion-Core) ───────
// Only translations currently available in that source are mapped.
const YOUVERSION_MAP = {
  'NIV':  'NIV',
  'NLT':  'NLT',
  'KJV':  'KJV',
  'AMP':  'AMP',
  'AMPC': 'AMPC',
  'ASV':  'ASV',
  'GNV':  2163,
  'CPDV': 'CPDV',
  'HINOVBSI': 1683,
  'TAOVBSI':  339,
  'IRVTEL':   1895,
  'MALOVBSI': 1693,
  'MALCLBSI': 1685,
};

// ── Bible reference language selector ────────────────────────────────────────
const REFERENCE_LANGUAGES = [
  { value: 'en', label: 'English' },
  { value: 'hi', label: 'Hindi (हिन्दी)' },
  { value: 'ta', label: 'Tamil (தமிழ்)' },
  { value: 'te', label: 'Telugu (తెలుగు)' },
  { value: 'ml', label: 'Malayalam (മലയാളം)' },
  { value: 'kn', label: 'Kannada (ಕನ್ನಡ)' },
];

// Reference book names for bilingual display (English + selected language).
// Fallback is English when a book is not listed for a language.
const BOOK_NAME_I18N = {
  hi: {
    'Genesis': 'उत्पत्ति',
    'Exodus': 'निर्गमन',
    'Leviticus': 'लैव्यव्यवस्था',
    'Numbers': 'गिनती',
    'Deuteronomy': 'व्यवस्थाविवरण',
    'Joshua': 'यहोशू',
    'Judges': 'न्यायियों',
    'Ruth': 'रूत',
    '1 Samuel': '1 शमूएल',
    '2 Samuel': '2 शमूएल',
    '1 Kings': '1 राजाओं',
    '2 Kings': '2 राजाओं',
    '1 Chronicles': '1 इतिहास',
    '2 Chronicles': '2 इतिहास',
    'Ezra': 'एज्रा',
    'Nehemiah': 'नहेम्याह',
    'Esther': 'एस्तेर',
    'Job': 'अय्यूब',
    'Psalms': 'भजन संहिता',
    'Proverbs': 'नीतिवचन',
    'Ecclesiastes': 'सभोपदेशक',
    'Song of Solomon': 'श्रेष्ठगीत',
    'Isaiah': 'यशायाह',
    'Jeremiah': 'यिर्मयाह',
    'Lamentations': 'विलापगीत',
    'Ezekiel': 'यहेजकेल',
    'Daniel': 'दानिय्येल',
    'Hosea': 'होशे',
    'Joel': 'योएल',
    'Amos': 'आमोस',
    'Obadiah': 'ओबद्याह',
    'Jonah': 'योना',
    'Micah': 'मीका',
    'Nahum': 'नहूम',
    'Habakkuk': 'हबक्कूक',
    'Zephaniah': 'सपन्याह',
    'Haggai': 'हाग्गै',
    'Zechariah': 'जकर्याह',
    'Malachi': 'मलाकी',
    'Matthew': 'मत्ती',
    'Mark': 'मरकुस',
    'Luke': 'लूका',
    'John': 'यूहन्ना',
    'Acts': 'प्रेरितों',
    'Romans': 'रोमियों',
    '1 Corinthians': '1 कुरिन्थियों',
    '2 Corinthians': '2 कुरिन्थियों',
    'Galatians': 'गलातियों',
    'Ephesians': 'इफिसियों',
    'Philippians': 'फिलिप्पियों',
    'Colossians': 'कुलुस्सियों',
    '1 Thessalonians': '1 थिस्सलुनीकियों',
    '2 Thessalonians': '2 थिस्सलुनीकियों',
    '1 Timothy': '1 तीमुथियुस',
    '2 Timothy': '2 तीमुथियुस',
    'Titus': 'तीतुस',
    'Philemon': 'फिलेमोन',
    'Hebrews': 'इब्रानियों',
    'James': 'याकूब',
    '1 Peter': '1 पतरस',
    '2 Peter': '2 पतरस',
    '1 John': '1 यूहन्ना',
    '2 John': '2 यूहन्ना',
    '3 John': '3 यूहन्ना',
    'Jude': 'यहूदा',
    'Revelation': 'प्रकाशितवाक्य'
  },
  ta: {
    'Genesis': 'ஆதியாகமம்',
    'Exodus': 'யாத்திராகமம்',
    'Leviticus': 'லேவியராகமம்',
    'Numbers': 'எண்ணாகமம்',
    'Deuteronomy': 'உபாகமம்',
    'Joshua': 'யோசுவா',
    'Judges': 'நியாயாதிபதிகள்',
    'Ruth': 'ரூத்',
    '1 Samuel': '1 சாமுவேல்',
    '2 Samuel': '2 சாமுவேல்',
    '1 Kings': '1 இராஜாக்கள்',
    '2 Kings': '2 இராஜாக்கள்',
    '1 Chronicles': '1 நாளாகமம்',
    '2 Chronicles': '2 நாளாகமம்',
    'Ezra': 'எஸ்றா',
    'Nehemiah': 'நெகேமியா',
    'Esther': 'எஸ்தர்',
    'Job': 'யோபு',
    'Psalms': 'சங்கீதம்',
    'Proverbs': 'நீதிமொழிகள்',
    'Ecclesiastes': 'பிரசங்கி',
    'Song of Solomon': 'உன்னதப்பாட்டு',
    'Isaiah': 'ஏசாயா',
    'Jeremiah': 'எரேமியா',
    'Lamentations': 'புலம்பல்',
    'Ezekiel': 'எசேக்கியேல்',
    'Daniel': 'தானியேல்',
    'Hosea': 'ஓசியா',
    'Joel': 'யோவேல்',
    'Amos': 'ஆமோஸ்',
    'Obadiah': 'ஒபதியா',
    'Jonah': 'யோனா',
    'Micah': 'மீகா',
    'Nahum': 'நாகூம்',
    'Habakkuk': 'ஆபகூக்',
    'Zephaniah': 'செப்பனியா',
    'Haggai': 'ஆகாய்',
    'Zechariah': 'சகரியா',
    'Malachi': 'மல்கியா',
    'Matthew': 'மத்தேயு',
    'Mark': 'மாற்கு',
    'Luke': 'லூக்கா',
    'John': 'யோவான்',
    'Acts': 'அப்போஸ்தலர்',
    'Romans': 'ரோமர்',
    '1 Corinthians': '1 கொரிந்தியர்',
    '2 Corinthians': '2 கொரிந்தியர்',
    'Galatians': 'கலாத்தியர்',
    'Ephesians': 'எபேசியர்',
    'Philippians': 'பிலிப்பியர்',
    'Colossians': 'கொலோசெயர்',
    '1 Thessalonians': '1 தெசலோனிக்கேயர்',
    '2 Thessalonians': '2 தெசலோனிக்கேயர்',
    '1 Timothy': '1 தீமோத்தேயு',
    '2 Timothy': '2 தீமோத்தேயு',
    'Titus': 'தீத்து',
    'Philemon': 'பிலேமோன்',
    'Hebrews': 'எபிரெயர்',
    'James': 'யாக்கோபு',
    '1 Peter': '1 பேதுரு',
    '2 Peter': '2 பேதுரு',
    '1 John': '1 யோவான்',
    '2 John': '2 யோவான்',
    '3 John': '3 யோவான்',
    'Jude': 'யூதா',
    'Revelation': 'வெளிப்படுத்தின விசேஷம்'
  },
  te: {
    'Genesis': 'ఆది',
    'Exodus': 'నిర్గమ',
    'Leviticus': 'లేవీ',
    'Numbers': 'సంఖ్యా',
    'Deuteronomy': 'ద్వితీ',
    'Joshua': 'యెహో',
    'Judges': 'న్యాయాధి',
    'Ruth': 'రూతు',
    '1 Samuel': '1 సమూ',
    '2 Samuel': '2 సమూ',
    '1 Kings': '1 రాజులు',
    '2 Kings': '2 రాజులు',
    '1 Chronicles': '1 దిన',
    '2 Chronicles': '2 దిన',
    'Ezra': 'ఎజ్రా',
    'Nehemiah': 'నెహెమ్యా',
    'Esther': 'ఎస్తేరు',
    'Job': 'యోబు',
    'Psalms': 'కీర్తన',
    'Proverbs': 'సామెత',
    'Ecclesiastes': 'ప్రసంగి',
    'Song of Solomon': 'పరమ',
    'Isaiah': 'యెషయా',
    'Jeremiah': 'యిర్మీయా',
    'Lamentations': 'విలాప',
    'Ezekiel': 'యెహె',
    'Daniel': 'దాని',
    'Hosea': 'హోషే',
    'Joel': 'యోవే',
    'Amos': 'ఆమోసు',
    'Obadiah': 'ఓబద్యా',
    'Jonah': 'యోనా',
    'Micah': 'మీకా',
    'Nahum': 'నహూ',
    'Habakkuk': 'హబ',
    'Zephaniah': 'జెఫన్యా',
    'Haggai': 'హగ్గయి',
    'Zechariah': 'జెకర్యా',
    'Malachi': 'మలాకీ',
    'Matthew': 'మత్తయి',
    'Mark': 'మార్కు',
    'Luke': 'లూకా',
    'John': 'యోహాను',
    'Acts': 'అపొస్తలుల కార్యములు',
    'Romans': 'రోమా పత్రిక',
    '1 Corinthians': '1 కొరింతీ పత్రిక',
    '2 Corinthians': '2 కొరింతీ పత్రిక',
    'Galatians': 'గలతీ పత్రిక',
    'Ephesians': 'ఎఫెసీ పత్రిక',
    'Philippians': 'ఫిలిప్పీ పత్రిక',
    'Colossians': 'కొలస్సీ పత్రిక',
    '1 Thessalonians': '1 తెస్సలోనిక పత్రిక',
    '2 Thessalonians': '2 తెస్సలోనిక పత్రిక',
    '1 Timothy': '1 తిమోతి పత్రిక',
    '2 Timothy': '2 తిమోతి పత్రిక',
    'Titus': 'తీతు పత్రిక',
    'Philemon': 'ఫిలేమోను పత్రిక',
    'Hebrews': 'హెబ్రీ పత్రిక',
    'James': 'యాకోబు పత్రిక',
    '1 Peter': '1 పేతురు పత్రిక',
    '2 Peter': '2 పేతురు పత్రిక',
    '1 John': '1 యోహాను పత్రిక',
    '2 John': '2 యోహాను పత్రిక',
    '3 John': '3 యోహాను పత్రిక',
    'Jude': 'యూదా పత్రిక',
    'Revelation': 'ప్రకటన గ్రంథం'
  },
  ml: {
    'Genesis': 'ഉൽപത്തി',
    'Exodus': 'പുറപ്പാട്',
    'Leviticus': 'ലേവ്യാപുസ്തകം',
    'Numbers': 'സംഖ്യാപുസ്തകം',
    'Deuteronomy': 'ആവർത്തനപുസ്തകം',
    'Joshua': 'യോശുവ',
    'Judges': 'ന്യായാധിപന്മാർ',
    'Ruth': 'രൂത്ത്',
    '1 Samuel': '1 ശമൂവേൽ',
    '2 Samuel': '2 ശമൂവേൽ',
    '1 Kings': '1 രാജാക്കന്മാർ',
    '2 Kings': '2 രാജാക്കന്മാർ',
    '1 Chronicles': '1 ദിനവൃത്താന്തം',
    '2 Chronicles': '2 ദിനവൃത്താന്തം',
    'Ezra': 'എസ്രാ',
    'Nehemiah': 'നെഹെമ്യാവ്',
    'Esther': 'എസ്ഥേർ',
    'Job': 'ഇയ്യോബ്',
    'Psalms': 'സങ്കീർത്തനങ്ങൾ',
    'Proverbs': 'സദൃശവാക്യങ്ങൾ',
    'Ecclesiastes': 'സഭാപ്രസംഗി',
    'Song of Solomon': 'ഉത്തമഗീതം',
    'Isaiah': 'യെശയ്യാവ്',
    'Jeremiah': 'യിരെമ്യാവ്',
    'Lamentations': 'വിലാപങ്ങൾ',
    'Ezekiel': 'യെഹെസ്കേൽ',
    'Daniel': 'ദാനീയേൽ',
    'Hosea': 'ഹോശേയ',
    'Joel': 'യോവേൽ',
    'Amos': 'ആമോസ്',
    'Obadiah': 'ഓബദ്യാവ്',
    'Jonah': 'യോനാ',
    'Micah': 'മീഖാ',
    'Nahum': 'നഹൂം',
    'Habakkuk': 'ഹബക്കൂക്',
    'Zephaniah': 'സെഫന്യാവ്',
    'Haggai': 'ഹഗ്ഗായി',
    'Zechariah': 'സെഖര്യാവ്',
    'Malachi': 'മലാഖി',
    'Matthew': 'മത്തായി',
    'Mark': 'മർക്കൊസ്',
    'Luke': 'ലൂക്കൊസ്',
    'John': 'യോഹന്നാൻ',
    'Acts': 'അപ്പൊ. പ്രവൃത്തികൾ',
    'Romans': 'റോമർ',
    '1 Corinthians': '1 കൊരിന്ത്യർ',
    '2 Corinthians': '2 കൊരിന്ത്യർ',
    'Galatians': 'ഗലാത്യർ',
    'Ephesians': 'എഫെസ്യർ',
    'Philippians': 'ഫിലിപ്പിയർ',
    'Colossians': 'കൊലൊസ്സ്യർ',
    '1 Thessalonians': '1 തെസ്സലൊനീക്യർ',
    '2 Thessalonians': '2 തെസ്സലൊനീക്യർ',
    '1 Timothy': '1 തിമൊഥെയൊസ്',
    '2 Timothy': '2 തിമൊഥെയൊസ്',
    'Titus': 'തീത്തൊസിന്',
    'Philemon': 'ഫിലേമൊന്',
    'Hebrews': 'എബ്രായർ',
    'James': 'യാക്കോബ്',
    '1 Peter': '1 പത്രൊസ്',
    '2 Peter': '2 പത്രൊസ്',
    '1 John': '1 യോഹന്നാൻ',
    '2 John': '2 യോഹന്നാൻ',
    '3 John': '3 യോഹന്നാൻ',
    'Jude': 'യൂദാ',
    'Revelation': 'വെളിപ്പാട്'
  },
  kn: {
    'Genesis': 'ಆದಿಕಾಂಡ',
    'Exodus': 'ವಿಮೋಚನಕಾಂಡ',
    'Leviticus': 'ಯಾಜಕಕಾಂಡ',
    'Numbers': 'ಅರಣ್ಯಕಾಂಡ',
    'Deuteronomy': 'ಧರ್ಮೋಪದೇಶಕಾಂಡ',
    'Joshua': 'ಯೆಹೋಶುವನು',
    'Judges': 'ನ್ಯಾಯಸ್ಥಾಪಕರು',
    'Ruth': 'ರೂತಳು',
    '1 Samuel': '1 ಸಮುವೇಲನು',
    '2 Samuel': '2 ಸಮುವೇಲನು',
    '1 Kings': '1 ರಾಜರುಗಳು',
    '2 Kings': '2 ರಾಜರುಗಳು',
    '1 Chronicles': '1 ಪೂರ್ವಕಾಲವೃತ್ತಾಂತ',
    '2 Chronicles': '2 ಪೂರ್ವಕಾಲವೃತ್ತಾಂತ',
    'Ezra': 'ಎಜ್ರ',
    'Nehemiah': 'ನೆಹೆಮೀಯ',
    'Esther': 'ಎಸ್ತೇರಳು',
    'Job': 'ಯೋಬನು',
    'Psalms': 'ಕೀರ್ತನೆಗಳು',
    'Proverbs': 'ಜ್ಞಾನೋಕ್ತಿಗಳು',
    'Ecclesiastes': 'ಪ್ರಸಂಗಿ',
    'Song of Solomon': 'ಪರಮ ಗೀತ',
    'Isaiah': 'ಯೆಶಾಯ',
    'Jeremiah': 'ಯೆರೆಮೀಯ',
    'Lamentations': 'ಪ್ರಲಾಪಗಳು',
    'Ezekiel': 'ಯೆಹೆಜ್ಕೇಲ',
    'Daniel': 'ದಾನಿಯೇಲ',
    'Hosea': 'ಹೋಶೇಯ',
    'Joel': 'ಯೋವೇಲ',
    'Amos': 'ಆಮೋಸ',
    'Obadiah': 'ಒಬದ್ಯ',
    'Jonah': 'ಯೋನ',
    'Micah': 'ಮೀಕ',
    'Nahum': 'ನಹೂಮ',
    'Habakkuk': 'ಹಬಕ್ಕೂಕ',
    'Zephaniah': 'ಚೆಫನ್ಯ',
    'Haggai': 'ಹಗ್ಗಾಯ',
    'Zechariah': 'ಜೆಕರ್ಯ',
    'Malachi': 'ಮಲಾಕಿ',
    'Matthew': 'ಮತ್ತಾಯ',
    'Mark': 'ಮಾರ್ಕ',
    'Luke': 'ಲೂಕ',
    'John': 'ಯೋಹಾನ',
    'Acts': 'ಅಪೊಸ್ತಲರ ಕಾರ್ಯಗಳು',
    'Romans': 'ರೋಮ್ನಗರದವರಿಗೆ',
    '1 Corinthians': '1 ಕೊರಿಂಥದವರಿಗೆ',
    '2 Corinthians': '2 ಕೊರಿಂಥದವರಿಗೆ',
    'Galatians': 'ಗಲಾತ್ಯದವರಿಗೆ',
    'Ephesians': 'ಎಫೆಸದವರಿಗೆ',
    'Philippians': 'ಫಿಲಿಪ್ಪಿಯವರಿಗೆ',
    'Colossians': 'ಕೊಲೊಸ್ಸೆಯವರಿಗೆ',
    '1 Thessalonians': '1 ಥೆಸಲೋನಿಕದವರಿಗೆ',
    '2 Thessalonians': '2 ಥೆಸಲೋನಿಕದವರಿಗೆ',
    '1 Timothy': '1 ತಿಮೊಥೆಯನಿಗೆ',
    '2 Timothy': '2 ತಿಮೊಥೆಯನಿಗೆ',
    'Titus': 'ತೀತನಿಗೆ',
    'Philemon': 'ಫಿಲೆಮೋನನಿಗೆ',
    'Hebrews': 'ಇಬ್ರಿಯರಿಗೆ',
    'James': 'ಯಾಕೋಬನು',
    '1 Peter': '1 ಪೇತ್ರನು',
    '2 Peter': '2 ಪೇತ್ರನು',
    '1 John': '1 ಯೋಹಾನ',
    '2 John': '2 ಯೋಹಾನ',
    '3 John': '3 ಯೋಹಾನ',
    'Jude': 'ಯೂದನು',
    'Revelation': 'ಪ್ರಕಟನೆ'
  },
};

// ── api.bible  (https://rest.api.bible — requires API key) ────────────────────
// Maps our translation abbreviations to their Bible ID on rest.api.bible.
// Only translations confirmed available under the configured API key are listed.
const APIBIBLE_IDS = {
  'AMP':    'a81b73293d3080c9-01',   // Amplified Bible
  'MSG':    '6f11a7de016f942e-01',   // The Message
  'NASB':   'b8ee27bcd1cae43a-01',   // New American Standard Bible 1995
  'NASB95': 'b8ee27bcd1cae43a-01',   // NASB 1995 (same text)
  'LSV':    '01b29f4b342acc35-01',   // Literal Standard Version
};

// ── bible.helloao.org  (free, no key, fetches full chapter) ──────────────────
// Maps our translation abbreviations to helloao.org translation IDs.
// API: https://bible.helloao.org/api/{id}/{USFM_BOOK}/{chapter}.json
const HELLOAO_MAP = {
  'BSB': 'BSB',    // Berean Standard Bible
};

// USFM book codes used by api.bible passage IDs  (e.g. "John 3:16" → "JHN.3.16")
const USFM_CODES = {
  'Genesis':         'GEN', 'Exodus':          'EXO', 'Leviticus':       'LEV',
  'Numbers':         'NUM', 'Deuteronomy':     'DEU', 'Joshua':          'JOS',
  'Judges':          'JDG', 'Ruth':            'RUT', '1 Samuel':        '1SA',
  '2 Samuel':        '2SA', '1 Kings':         '1KI', '2 Kings':         '2KI',
  '1 Chronicles':    '1CH', '2 Chronicles':    '2CH', 'Ezra':            'EZR',
  'Nehemiah':        'NEH', 'Esther':          'EST', 'Job':             'JOB',
  'Psalms':          'PSA', 'Proverbs':        'PRO', 'Ecclesiastes':    'ECC',
  'Song of Solomon': 'SNG', 'Isaiah':          'ISA', 'Jeremiah':        'JER',
  'Lamentations':    'LAM', 'Ezekiel':         'EZK', 'Daniel':          'DAN',
  'Hosea':           'HOS', 'Joel':            'JOL', 'Amos':            'AMO',
  'Obadiah':         'OBA', 'Jonah':           'JON', 'Micah':           'MIC',
  'Nahum':           'NAM', 'Habakkuk':        'HAB', 'Zephaniah':       'ZEP',
  'Haggai':          'HAG', 'Zechariah':       'ZEC', 'Malachi':         'MAL',
  'Matthew':         'MAT', 'Mark':            'MRK', 'Luke':            'LUK',
  'John':            'JHN', 'Acts':            'ACT', 'Romans':          'ROM',
  '1 Corinthians':   '1CO', '2 Corinthians':   '2CO', 'Galatians':       'GAL',
  'Ephesians':       'EPH', 'Philippians':     'PHP', 'Colossians':      'COL',
  '1 Thessalonians': '1TH', '2 Thessalonians': '2TH', '1 Timothy':       '1TI',
  '2 Timothy':       '2TI', 'Titus':           'TIT', 'Philemon':        'PHM',
  'Hebrews':         'HEB', 'James':           'JAS', '1 Peter':         '1PE',
  '2 Peter':         '2PE', '1 John':          '1JN', '2 John':          '2JN',
  '3 John':          '3JN', 'Jude':            'JUD', 'Revelation':      'REV',
};

// Font definitions for the font picker
// Google Fonts are loaded in index.html / output.html <head>
const FONT_OPTIONS = [
  // ── Display / Broadcast (Roman/Inscriptional) ──────────────────────────────
  { label: 'Cinzel  —  Trajan-style Roman',         value: "'Cinzel', serif",              group: 'Display',      weights: [400, 700] },
  { label: 'Cinzel Decorative  —  Ornate Roman',    value: "'Cinzel Decorative', cursive",  group: 'Display',      weights: [400, 700] },
  { label: 'Trajan Pro alt: Cinzel Bold',            value: "'Cinzel', serif",              group: 'Display',      weights: [400, 700] },
  // ── Elegant Serif ──────────────────────────────────────────────────────────
  { label: 'Playfair Display  —  Editorial Serif',   value: "'Playfair Display', serif",    group: 'Elegant Serif', weights: [400, 700] },
  { label: 'Cormorant Garamond  —  Refined Serif',   value: "'Cormorant Garamond', serif",  group: 'Elegant Serif', weights: [400, 700] },
  { label: 'EB Garamond  —  Classic Book',           value: "'EB Garamond', serif",         group: 'Elegant Serif', weights: [400, 700] },
  { label: 'Libre Baskerville  —  Baskerville',      value: "'Libre Baskerville', serif",   group: 'Elegant Serif', weights: [400, 700] },
  { label: 'Lora  —  Contemporary Serif',            value: "'Lora', serif",                group: 'Elegant Serif', weights: [400, 700] },
  { label: 'Merriweather  —  Screen Serif',          value: "'Merriweather', serif",        group: 'Elegant Serif', weights: [400, 700] },
  { label: 'Crimson Pro  —  Literary Serif',         value: "'Crimson Pro', serif",         group: 'Elegant Serif', weights: [400, 700] },
  // ── Modern Sans ────────────────────────────────────────────────────────────
  { label: 'Inter  —  UI Sans',                       value: "'Inter', sans-serif",          group: 'Modern Sans',   weights: [300, 400, 500, 600, 700, 800, 900] },
  { label: 'Geist Variable  —  UI Sans',             value: "'Geist', sans-serif",          group: 'Modern Sans',   weights: [300, 400, 500, 600, 700, 800, 900] },
  { label: 'Nunito  —  Rounded Sans',                value: "'Nunito', sans-serif",         group: 'Modern Sans',   weights: [300, 400, 500, 600, 700, 800, 900] },
  { label: 'Quicksand  —  Rounded Geometric',        value: "'Quicksand', sans-serif",      group: 'Modern Sans',   weights: [300, 400, 500, 600, 700] },
  { label: 'Archivo  —  Neutral Sans',               value: "'Archivo', sans-serif",        group: 'Modern Sans',   weights: [400, 500, 600, 700, 800] },
  { label: 'Rubik  —  Humanist Sans',                value: "'Rubik', sans-serif",          group: 'Modern Sans',   weights: [300, 400, 500, 600, 700, 800, 900] },
  { label: 'Lexend  —  Readability Sans',            value: "'Lexend', sans-serif",         group: 'Modern Sans',   weights: [300, 400, 500, 600, 700, 800] },
  { label: 'Albert Sans  —  Grotesk Sans',           value: "'Albert Sans', sans-serif",    group: 'Modern Sans',   weights: [300, 400, 500, 600, 700, 800, 900] },
  { label: 'Poppins  —  Geometric Sans',             value: "'Poppins', sans-serif",        group: 'Modern Sans',   weights: [300, 400, 500, 600, 700, 800, 900] },
  { label: 'Rethink Sans  —  Contemporary Sans',     value: "'Rethink Sans', sans-serif",   group: 'Modern Sans',   weights: [400, 500, 600, 700, 800] },
  { label: 'Josefin Sans  —  Elegant Geometric',     value: "'Josefin Sans', sans-serif",   group: 'Modern Sans',   weights: [400, 700] },
  { label: 'Montserrat  —  Geometric Sans',          value: "'Montserrat', sans-serif",     group: 'Modern Sans',   weights: [400, 700] },
  { label: 'Raleway  —  Stylish Thin Sans',          value: "'Raleway', sans-serif",        group: 'Modern Sans',   weights: [400, 700] },
  { label: 'Oswald  —  Condensed Sans',              value: "'Oswald', sans-serif",         group: 'Modern Sans',   weights: [400, 700] },
  { label: 'Bebas Neue  —  Bold Display',            value: "'Bebas Neue', cursive",        group: 'Modern Sans',   weights: [400] },
  // ── Display Sans ───────────────────────────────────────────────────────────
  { label: 'Concert One  —  Playful Display',        value: "'Concert One', cursive",       group: 'Display Sans',  weights: [400] },
  { label: 'Unbounded  —  Tech Display',             value: "'Unbounded', sans-serif",      group: 'Display Sans',  weights: [300, 400, 500, 600, 700, 800, 900] },
  { label: 'Anton  —  Impact Display',               value: "'Anton', sans-serif",          group: 'Display Sans',  weights: [400] },
  // ── Indic Script ───────────────────────────────────────────────────────────
  { label: 'Noto Sans Devanagari  —  Hindi',         value: "'Noto Sans Devanagari', sans-serif", group: 'Indic Script', weights: [400, 700] },
  { label: 'Noto Sans Tamil  —  Tamil',              value: "'Noto Sans Tamil', sans-serif",      group: 'Indic Script', weights: [400, 700] },
  { label: 'Noto Sans Telugu  —  Telugu',            value: "'Noto Sans Telugu', sans-serif",     group: 'Indic Script', weights: [400, 700] },
  { label: 'Noto Sans Malayalam  —  Malayalam',      value: "'Noto Sans Malayalam', sans-serif",  group: 'Indic Script', weights: [400, 700] },
  { label: 'Noto Sans Kannada  —  Kannada',          value: "'Noto Sans Kannada', sans-serif",    group: 'Indic Script', weights: [400, 700] },
  // ── System / Standard ──────────────────────────────────────────────────────
  { label: 'System UI  —  Default',                  value: 'system-ui',                    group: 'System',        weights: [400, 500, 600, 700, 800, 900] },
  { label: 'Georgia  —  Classic Serif',              value: "'Georgia', serif",             group: 'System',        weights: [400, 700] },
  { label: 'Times New Roman',                        value: "'Times New Roman', serif",     group: 'System',        weights: [400, 700] },
  { label: 'Arial',                                  value: "'Arial', sans-serif",          group: 'System',        weights: [400, 700] },
  { label: 'Trebuchet MS',                           value: "'Trebuchet MS', sans-serif",   group: 'System',        weights: [400, 700] },
  { label: 'Verdana',                                value: "'Verdana', sans-serif",        group: 'System',        weights: [400, 700] },
];
